//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace PRETEST.WebReference1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AVTC_webserviceSoap", Namespace="http://tempuri.org/")]
    public partial class AVTC_webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_product_hOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_EM_BUOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPD_EM_BUOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_EM_BUOperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_WBEROperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_STCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_TVDROperationCompleted;
        
        private System.Threading.SendOrPostCallback get_testOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_DC_CHECKOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_DC_CHECKOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_EMP_IDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_HDCP_keyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_HDCPOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadADCValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback CHK_MES_ROUTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_MES_STATIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_DIXIE_MACOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPD_DIXIE_MACOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_sn_kppnOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AVTC_webservice() {
            this.Url = "http://10.2.100.72:2001/AVTC_webservice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_product_hCompletedEventHandler get_product_hCompleted;
        
        /// <remarks/>
        public event INS_EM_BUCompletedEventHandler INS_EM_BUCompleted;
        
        /// <remarks/>
        public event UPD_EM_BUCompletedEventHandler UPD_EM_BUCompleted;
        
        /// <remarks/>
        public event QRY_EM_BUCompletedEventHandler QRY_EM_BUCompleted;
        
        /// <remarks/>
        public event SD_WBERCompletedEventHandler SD_WBERCompleted;
        
        /// <remarks/>
        public event SD_STCKCompletedEventHandler SD_STCKCompleted;
        
        /// <remarks/>
        public event SD_TVDRCompletedEventHandler SD_TVDRCompleted;
        
        /// <remarks/>
        public event get_testCompletedEventHandler get_testCompleted;
        
        /// <remarks/>
        public event INS_DC_CHECKCompletedEventHandler INS_DC_CHECKCompleted;
        
        /// <remarks/>
        public event QRY_DC_CHECKCompletedEventHandler QRY_DC_CHECKCompleted;
        
        /// <remarks/>
        public event QRY_EMP_IDCompletedEventHandler QRY_EMP_IDCompleted;
        
        /// <remarks/>
        public event Get_HDCP_keyCompletedEventHandler Get_HDCP_keyCompleted;
        
        /// <remarks/>
        public event Check_HDCPCompletedEventHandler Check_HDCPCompleted;
        
        /// <remarks/>
        public event UploadADCValueCompletedEventHandler UploadADCValueCompleted;
        
        /// <remarks/>
        public event CHK_MES_ROUTECompletedEventHandler CHK_MES_ROUTECompleted;
        
        /// <remarks/>
        public event INS_MES_STATIONCompletedEventHandler INS_MES_STATIONCompleted;
        
        /// <remarks/>
        public event GET_DIXIE_MACCompletedEventHandler GET_DIXIE_MACCompleted;
        
        /// <remarks/>
        public event UPD_DIXIE_MACCompletedEventHandler UPD_DIXIE_MACCompleted;
        
        /// <remarks/>
        public event QRY_sn_kppnCompletedEventHandler QRY_sn_kppnCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_product_h", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_product_h(string sn) {
            object[] results = this.Invoke("get_product_h", new object[] {
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_product_hAsync(string sn) {
            this.get_product_hAsync(sn, null);
        }
        
        /// <remarks/>
        public void get_product_hAsync(string sn, object userState) {
            if ((this.get_product_hOperationCompleted == null)) {
                this.get_product_hOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_product_hOperationCompleted);
            }
            this.InvokeAsync("get_product_h", new object[] {
                        sn}, this.get_product_hOperationCompleted, userState);
        }
        
        private void Onget_product_hOperationCompleted(object arg) {
            if ((this.get_product_hCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_product_hCompleted(this, new get_product_hCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_EM_BU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_EM_BU(string x_trid, string x_workorder, string x_model, string x_bu, string x_x, string x_y, string x_lv, string x_okng, string x_eventtime) {
            object[] results = this.Invoke("INS_EM_BU", new object[] {
                        x_trid,
                        x_workorder,
                        x_model,
                        x_bu,
                        x_x,
                        x_y,
                        x_lv,
                        x_okng,
                        x_eventtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_EM_BUAsync(string x_trid, string x_workorder, string x_model, string x_bu, string x_x, string x_y, string x_lv, string x_okng, string x_eventtime) {
            this.INS_EM_BUAsync(x_trid, x_workorder, x_model, x_bu, x_x, x_y, x_lv, x_okng, x_eventtime, null);
        }
        
        /// <remarks/>
        public void INS_EM_BUAsync(string x_trid, string x_workorder, string x_model, string x_bu, string x_x, string x_y, string x_lv, string x_okng, string x_eventtime, object userState) {
            if ((this.INS_EM_BUOperationCompleted == null)) {
                this.INS_EM_BUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_EM_BUOperationCompleted);
            }
            this.InvokeAsync("INS_EM_BU", new object[] {
                        x_trid,
                        x_workorder,
                        x_model,
                        x_bu,
                        x_x,
                        x_y,
                        x_lv,
                        x_okng,
                        x_eventtime}, this.INS_EM_BUOperationCompleted, userState);
        }
        
        private void OnINS_EM_BUOperationCompleted(object arg) {
            if ((this.INS_EM_BUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_EM_BUCompleted(this, new INS_EM_BUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPD_EM_BU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UPD_EM_BU(string x_bu, string x_x, string x_y, string x_lv, string x_eventtime, string x_trid) {
            object[] results = this.Invoke("UPD_EM_BU", new object[] {
                        x_bu,
                        x_x,
                        x_y,
                        x_lv,
                        x_eventtime,
                        x_trid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPD_EM_BUAsync(string x_bu, string x_x, string x_y, string x_lv, string x_eventtime, string x_trid) {
            this.UPD_EM_BUAsync(x_bu, x_x, x_y, x_lv, x_eventtime, x_trid, null);
        }
        
        /// <remarks/>
        public void UPD_EM_BUAsync(string x_bu, string x_x, string x_y, string x_lv, string x_eventtime, string x_trid, object userState) {
            if ((this.UPD_EM_BUOperationCompleted == null)) {
                this.UPD_EM_BUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPD_EM_BUOperationCompleted);
            }
            this.InvokeAsync("UPD_EM_BU", new object[] {
                        x_bu,
                        x_x,
                        x_y,
                        x_lv,
                        x_eventtime,
                        x_trid}, this.UPD_EM_BUOperationCompleted, userState);
        }
        
        private void OnUPD_EM_BUOperationCompleted(object arg) {
            if ((this.UPD_EM_BUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPD_EM_BUCompleted(this, new UPD_EM_BUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_EM_BU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_EM_BU(string x_con) {
            object[] results = this.Invoke("QRY_EM_BU", new object[] {
                        x_con});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_EM_BUAsync(string x_con) {
            this.QRY_EM_BUAsync(x_con, null);
        }
        
        /// <remarks/>
        public void QRY_EM_BUAsync(string x_con, object userState) {
            if ((this.QRY_EM_BUOperationCompleted == null)) {
                this.QRY_EM_BUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_EM_BUOperationCompleted);
            }
            this.InvokeAsync("QRY_EM_BU", new object[] {
                        x_con}, this.QRY_EM_BUOperationCompleted, userState);
        }
        
        private void OnQRY_EM_BUOperationCompleted(object arg) {
            if ((this.QRY_EM_BUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_EM_BUCompleted(this, new QRY_EM_BUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_WBER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_WBER(string x_meseid, string x_sn, string x_user, string pf, string x_comment) {
            object[] results = this.Invoke("SD_WBER", new object[] {
                        x_meseid,
                        x_sn,
                        x_user,
                        pf,
                        x_comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_WBERAsync(string x_meseid, string x_sn, string x_user, string pf, string x_comment) {
            this.SD_WBERAsync(x_meseid, x_sn, x_user, pf, x_comment, null);
        }
        
        /// <remarks/>
        public void SD_WBERAsync(string x_meseid, string x_sn, string x_user, string pf, string x_comment, object userState) {
            if ((this.SD_WBEROperationCompleted == null)) {
                this.SD_WBEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_WBEROperationCompleted);
            }
            this.InvokeAsync("SD_WBER", new object[] {
                        x_meseid,
                        x_sn,
                        x_user,
                        pf,
                        x_comment}, this.SD_WBEROperationCompleted, userState);
        }
        
        private void OnSD_WBEROperationCompleted(object arg) {
            if ((this.SD_WBERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_WBERCompleted(this, new SD_WBERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_STCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_STCK(string x_meseid, string x_sn, string x_user) {
            object[] results = this.Invoke("SD_STCK", new object[] {
                        x_meseid,
                        x_sn,
                        x_user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_STCKAsync(string x_meseid, string x_sn, string x_user) {
            this.SD_STCKAsync(x_meseid, x_sn, x_user, null);
        }
        
        /// <remarks/>
        public void SD_STCKAsync(string x_meseid, string x_sn, string x_user, object userState) {
            if ((this.SD_STCKOperationCompleted == null)) {
                this.SD_STCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_STCKOperationCompleted);
            }
            this.InvokeAsync("SD_STCK", new object[] {
                        x_meseid,
                        x_sn,
                        x_user}, this.SD_STCKOperationCompleted, userState);
        }
        
        private void OnSD_STCKOperationCompleted(object arg) {
            if ((this.SD_STCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_STCKCompleted(this, new SD_STCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_TVDR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_TVDR(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment) {
            object[] results = this.Invoke("SD_TVDR", new object[] {
                        x_meseid,
                        x_sn,
                        CD,
                        TYPE,
                        DV_ID,
                        x_user,
                        x_comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_TVDRAsync(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment) {
            this.SD_TVDRAsync(x_meseid, x_sn, CD, TYPE, DV_ID, x_user, x_comment, null);
        }
        
        /// <remarks/>
        public void SD_TVDRAsync(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment, object userState) {
            if ((this.SD_TVDROperationCompleted == null)) {
                this.SD_TVDROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_TVDROperationCompleted);
            }
            this.InvokeAsync("SD_TVDR", new object[] {
                        x_meseid,
                        x_sn,
                        CD,
                        TYPE,
                        DV_ID,
                        x_user,
                        x_comment}, this.SD_TVDROperationCompleted, userState);
        }
        
        private void OnSD_TVDROperationCompleted(object arg) {
            if ((this.SD_TVDRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_TVDRCompleted(this, new SD_TVDRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_test(string x_sql) {
            object[] results = this.Invoke("get_test", new object[] {
                        x_sql});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void get_testAsync(string x_sql) {
            this.get_testAsync(x_sql, null);
        }
        
        /// <remarks/>
        public void get_testAsync(string x_sql, object userState) {
            if ((this.get_testOperationCompleted == null)) {
                this.get_testOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_testOperationCompleted);
            }
            this.InvokeAsync("get_test", new object[] {
                        x_sql}, this.get_testOperationCompleted, userState);
        }
        
        private void Onget_testOperationCompleted(object arg) {
            if ((this.get_testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_testCompleted(this, new get_testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_DC_CHECK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_DC_CHECK(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code) {
            object[] results = this.Invoke("INS_DC_CHECK", new object[] {
                        x_trid,
                        x_workorder,
                        x_pn,
                        x_op,
                        x_info,
                        x_okng,
                        x_eventtime,
                        x_st_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_DC_CHECKAsync(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code) {
            this.INS_DC_CHECKAsync(x_trid, x_workorder, x_pn, x_op, x_info, x_okng, x_eventtime, x_st_code, null);
        }
        
        /// <remarks/>
        public void INS_DC_CHECKAsync(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code, object userState) {
            if ((this.INS_DC_CHECKOperationCompleted == null)) {
                this.INS_DC_CHECKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_DC_CHECKOperationCompleted);
            }
            this.InvokeAsync("INS_DC_CHECK", new object[] {
                        x_trid,
                        x_workorder,
                        x_pn,
                        x_op,
                        x_info,
                        x_okng,
                        x_eventtime,
                        x_st_code}, this.INS_DC_CHECKOperationCompleted, userState);
        }
        
        private void OnINS_DC_CHECKOperationCompleted(object arg) {
            if ((this.INS_DC_CHECKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_DC_CHECKCompleted(this, new INS_DC_CHECKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_DC_CHECK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_DC_CHECK(string con) {
            object[] results = this.Invoke("QRY_DC_CHECK", new object[] {
                        con});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_DC_CHECKAsync(string con) {
            this.QRY_DC_CHECKAsync(con, null);
        }
        
        /// <remarks/>
        public void QRY_DC_CHECKAsync(string con, object userState) {
            if ((this.QRY_DC_CHECKOperationCompleted == null)) {
                this.QRY_DC_CHECKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_DC_CHECKOperationCompleted);
            }
            this.InvokeAsync("QRY_DC_CHECK", new object[] {
                        con}, this.QRY_DC_CHECKOperationCompleted, userState);
        }
        
        private void OnQRY_DC_CHECKOperationCompleted(object arg) {
            if ((this.QRY_DC_CHECKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_DC_CHECKCompleted(this, new QRY_DC_CHECKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_EMP_ID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_EMP_ID(string card_no) {
            object[] results = this.Invoke("QRY_EMP_ID", new object[] {
                        card_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_EMP_IDAsync(string card_no) {
            this.QRY_EMP_IDAsync(card_no, null);
        }
        
        /// <remarks/>
        public void QRY_EMP_IDAsync(string card_no, object userState) {
            if ((this.QRY_EMP_IDOperationCompleted == null)) {
                this.QRY_EMP_IDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_EMP_IDOperationCompleted);
            }
            this.InvokeAsync("QRY_EMP_ID", new object[] {
                        card_no}, this.QRY_EMP_IDOperationCompleted, userState);
        }
        
        private void OnQRY_EMP_IDOperationCompleted(object arg) {
            if ((this.QRY_EMP_IDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_EMP_IDCompleted(this, new QRY_EMP_IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_HDCP_key", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_HDCP_key(string x_barcode) {
            object[] results = this.Invoke("Get_HDCP_key", new object[] {
                        x_barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_HDCP_keyAsync(string x_barcode) {
            this.Get_HDCP_keyAsync(x_barcode, null);
        }
        
        /// <remarks/>
        public void Get_HDCP_keyAsync(string x_barcode, object userState) {
            if ((this.Get_HDCP_keyOperationCompleted == null)) {
                this.Get_HDCP_keyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_HDCP_keyOperationCompleted);
            }
            this.InvokeAsync("Get_HDCP_key", new object[] {
                        x_barcode}, this.Get_HDCP_keyOperationCompleted, userState);
        }
        
        private void OnGet_HDCP_keyOperationCompleted(object arg) {
            if ((this.Get_HDCP_keyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_HDCP_keyCompleted(this, new Get_HDCP_keyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_HDCP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Check_HDCP(string x_barcode, string bksv, string x_used_flag) {
            object[] results = this.Invoke("Check_HDCP", new object[] {
                        x_barcode,
                        bksv,
                        x_used_flag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_HDCPAsync(string x_barcode, string bksv, string x_used_flag) {
            this.Check_HDCPAsync(x_barcode, bksv, x_used_flag, null);
        }
        
        /// <remarks/>
        public void Check_HDCPAsync(string x_barcode, string bksv, string x_used_flag, object userState) {
            if ((this.Check_HDCPOperationCompleted == null)) {
                this.Check_HDCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_HDCPOperationCompleted);
            }
            this.InvokeAsync("Check_HDCP", new object[] {
                        x_barcode,
                        bksv,
                        x_used_flag}, this.Check_HDCPOperationCompleted, userState);
        }
        
        private void OnCheck_HDCPOperationCompleted(object arg) {
            if ((this.Check_HDCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_HDCPCompleted(this, new Check_HDCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadADCValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadADCValue(string x_barcode, string x_LINE_CODE, string x_PROG_INFO, string x_PROG_STA, string x_OKNG) {
            object[] results = this.Invoke("UploadADCValue", new object[] {
                        x_barcode,
                        x_LINE_CODE,
                        x_PROG_INFO,
                        x_PROG_STA,
                        x_OKNG});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadADCValueAsync(string x_barcode, string x_LINE_CODE, string x_PROG_INFO, string x_PROG_STA, string x_OKNG) {
            this.UploadADCValueAsync(x_barcode, x_LINE_CODE, x_PROG_INFO, x_PROG_STA, x_OKNG, null);
        }
        
        /// <remarks/>
        public void UploadADCValueAsync(string x_barcode, string x_LINE_CODE, string x_PROG_INFO, string x_PROG_STA, string x_OKNG, object userState) {
            if ((this.UploadADCValueOperationCompleted == null)) {
                this.UploadADCValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadADCValueOperationCompleted);
            }
            this.InvokeAsync("UploadADCValue", new object[] {
                        x_barcode,
                        x_LINE_CODE,
                        x_PROG_INFO,
                        x_PROG_STA,
                        x_OKNG}, this.UploadADCValueOperationCompleted, userState);
        }
        
        private void OnUploadADCValueOperationCompleted(object arg) {
            if ((this.UploadADCValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadADCValueCompleted(this, new UploadADCValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CHK_MES_ROUTE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CHK_MES_ROUTE(string x_ST_ID, string x_SN) {
            object[] results = this.Invoke("CHK_MES_ROUTE", new object[] {
                        x_ST_ID,
                        x_SN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CHK_MES_ROUTEAsync(string x_ST_ID, string x_SN) {
            this.CHK_MES_ROUTEAsync(x_ST_ID, x_SN, null);
        }
        
        /// <remarks/>
        public void CHK_MES_ROUTEAsync(string x_ST_ID, string x_SN, object userState) {
            if ((this.CHK_MES_ROUTEOperationCompleted == null)) {
                this.CHK_MES_ROUTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCHK_MES_ROUTEOperationCompleted);
            }
            this.InvokeAsync("CHK_MES_ROUTE", new object[] {
                        x_ST_ID,
                        x_SN}, this.CHK_MES_ROUTEOperationCompleted, userState);
        }
        
        private void OnCHK_MES_ROUTEOperationCompleted(object arg) {
            if ((this.CHK_MES_ROUTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CHK_MES_ROUTECompleted(this, new CHK_MES_ROUTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_MES_STATION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_MES_STATION(string x_ST_ID, string x_SN, string x_user, string x_defect) {
            object[] results = this.Invoke("INS_MES_STATION", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_user,
                        x_defect});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_MES_STATIONAsync(string x_ST_ID, string x_SN, string x_user, string x_defect) {
            this.INS_MES_STATIONAsync(x_ST_ID, x_SN, x_user, x_defect, null);
        }
        
        /// <remarks/>
        public void INS_MES_STATIONAsync(string x_ST_ID, string x_SN, string x_user, string x_defect, object userState) {
            if ((this.INS_MES_STATIONOperationCompleted == null)) {
                this.INS_MES_STATIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_MES_STATIONOperationCompleted);
            }
            this.InvokeAsync("INS_MES_STATION", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_user,
                        x_defect}, this.INS_MES_STATIONOperationCompleted, userState);
        }
        
        private void OnINS_MES_STATIONOperationCompleted(object arg) {
            if ((this.INS_MES_STATIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_MES_STATIONCompleted(this, new INS_MES_STATIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_DIXIE_MAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_DIXIE_MAC(string sn, string use_mode) {
            object[] results = this.Invoke("GET_DIXIE_MAC", new object[] {
                        sn,
                        use_mode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_DIXIE_MACAsync(string sn, string use_mode) {
            this.GET_DIXIE_MACAsync(sn, use_mode, null);
        }
        
        /// <remarks/>
        public void GET_DIXIE_MACAsync(string sn, string use_mode, object userState) {
            if ((this.GET_DIXIE_MACOperationCompleted == null)) {
                this.GET_DIXIE_MACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_DIXIE_MACOperationCompleted);
            }
            this.InvokeAsync("GET_DIXIE_MAC", new object[] {
                        sn,
                        use_mode}, this.GET_DIXIE_MACOperationCompleted, userState);
        }
        
        private void OnGET_DIXIE_MACOperationCompleted(object arg) {
            if ((this.GET_DIXIE_MACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_DIXIE_MACCompleted(this, new GET_DIXIE_MACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPD_DIXIE_MAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UPD_DIXIE_MAC(string sn, string mac, string use_mode) {
            object[] results = this.Invoke("UPD_DIXIE_MAC", new object[] {
                        sn,
                        mac,
                        use_mode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPD_DIXIE_MACAsync(string sn, string mac, string use_mode) {
            this.UPD_DIXIE_MACAsync(sn, mac, use_mode, null);
        }
        
        /// <remarks/>
        public void UPD_DIXIE_MACAsync(string sn, string mac, string use_mode, object userState) {
            if ((this.UPD_DIXIE_MACOperationCompleted == null)) {
                this.UPD_DIXIE_MACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPD_DIXIE_MACOperationCompleted);
            }
            this.InvokeAsync("UPD_DIXIE_MAC", new object[] {
                        sn,
                        mac,
                        use_mode}, this.UPD_DIXIE_MACOperationCompleted, userState);
        }
        
        private void OnUPD_DIXIE_MACOperationCompleted(object arg) {
            if ((this.UPD_DIXIE_MACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPD_DIXIE_MACCompleted(this, new UPD_DIXIE_MACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_sn_kppn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_sn_kppn(string x_sn) {
            object[] results = this.Invoke("QRY_sn_kppn", new object[] {
                        x_sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_sn_kppnAsync(string x_sn) {
            this.QRY_sn_kppnAsync(x_sn, null);
        }
        
        /// <remarks/>
        public void QRY_sn_kppnAsync(string x_sn, object userState) {
            if ((this.QRY_sn_kppnOperationCompleted == null)) {
                this.QRY_sn_kppnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_sn_kppnOperationCompleted);
            }
            this.InvokeAsync("QRY_sn_kppn", new object[] {
                        x_sn}, this.QRY_sn_kppnOperationCompleted, userState);
        }
        
        private void OnQRY_sn_kppnOperationCompleted(object arg) {
            if ((this.QRY_sn_kppnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_sn_kppnCompleted(this, new QRY_sn_kppnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void get_product_hCompletedEventHandler(object sender, get_product_hCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_product_hCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_product_hCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void INS_EM_BUCompletedEventHandler(object sender, INS_EM_BUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_EM_BUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_EM_BUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UPD_EM_BUCompletedEventHandler(object sender, UPD_EM_BUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPD_EM_BUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPD_EM_BUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void QRY_EM_BUCompletedEventHandler(object sender, QRY_EM_BUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_EM_BUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_EM_BUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SD_WBERCompletedEventHandler(object sender, SD_WBERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_WBERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_WBERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SD_STCKCompletedEventHandler(object sender, SD_STCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_STCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_STCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SD_TVDRCompletedEventHandler(object sender, SD_TVDRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_TVDRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_TVDRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void get_testCompletedEventHandler(object sender, get_testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void INS_DC_CHECKCompletedEventHandler(object sender, INS_DC_CHECKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_DC_CHECKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_DC_CHECKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void QRY_DC_CHECKCompletedEventHandler(object sender, QRY_DC_CHECKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_DC_CHECKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_DC_CHECKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void QRY_EMP_IDCompletedEventHandler(object sender, QRY_EMP_IDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_EMP_IDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_EMP_IDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Get_HDCP_keyCompletedEventHandler(object sender, Get_HDCP_keyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_HDCP_keyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_HDCP_keyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Check_HDCPCompletedEventHandler(object sender, Check_HDCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_HDCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_HDCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UploadADCValueCompletedEventHandler(object sender, UploadADCValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadADCValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadADCValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CHK_MES_ROUTECompletedEventHandler(object sender, CHK_MES_ROUTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CHK_MES_ROUTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CHK_MES_ROUTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void INS_MES_STATIONCompletedEventHandler(object sender, INS_MES_STATIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_MES_STATIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_MES_STATIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GET_DIXIE_MACCompletedEventHandler(object sender, GET_DIXIE_MACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_DIXIE_MACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_DIXIE_MACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UPD_DIXIE_MACCompletedEventHandler(object sender, UPD_DIXIE_MACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPD_DIXIE_MACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPD_DIXIE_MACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void QRY_sn_kppnCompletedEventHandler(object sender, QRY_sn_kppnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_sn_kppnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_sn_kppnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591